stop: false # 暂停抓取节点
name_show_type: false # 在节点名称前添加如 [Vmess] 的标签
name_no_flags: false # 将节点名称中的地区旗帜改为文本地区码
name_show_src: false # 在节点名称前显示所属订阅编号 (订阅见 list_result.csv)
abfurls: # Adblock 规则黑名单
  - "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/adservers.txt"
  - "https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/adservers_firstparty.txt"
  - "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt"
  # - "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt"
  # - "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-ag.txt"
  # - "https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt"
  # - "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt"
  # - "https://anti-ad.net/adguard.txt"
  - "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt"
  - "https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock"
  # - "https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt"
  # - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt"
  # - "https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_lite.txt"
  - "https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt"
  # - "https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/domain.txt"
abfwhite: # Adblock 规则白名单
  - "https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-list.txt"
  - "file:///./abpwhite.txt"
name_map:
  ⛔ 广告拦截: adblock
  🚀 选择代理: proxy
  🌐 突破锁区: region
  🚨 病毒网站: malware
  DIRECT: direct
categories:
  redir: [Relay, 中转, OVERALL]
  JP: [JP, Japan, 日, 东京, 🇯🇵]
  US: [US, United States, 美, 🇺🇸]
  TW: [TW, Taiwan, 台, 🇹🇼, OVERALL]
  CN: [CN, China, 中国, 上海, 浙江, 广东, 深圳, 🇨🇳]
  HK: [HK, Hong Kong, 港, 🇭🇰]
  CA: [CA, Canada, 加拿大, 🇨🇦]
  FR: [FR, French, France, Paris, 法, 🇫🇷]
  SG: [SG, Singapore, 新加坡, 狮城, 🇸🇬]
  GB: [GB, UK, United Kindom, Britain, 英, 🇬🇧]
  KR: [KR, Korea, 韩, 🇰🇷]
  RU: [RU, Russia, 俄, 🇷🇺]
  DE: [DE, Germany, 德, 🇩🇪]
  SE: [SE, Sweden, 瑞典, 🇸🇪]
  CH: [CH, Switzerland, 瑞士, 🇨🇭]
  EE: [EE, Estonia, 爱沙尼亚, 🇪🇪]
categories_disp:
  JP: 🇯🇵 日本
  US: 🇺🇸 美国
  HK: 🇭🇰 香港
  TW: 🇨🇳 台湾
  SG: 🇸🇬 新加坡
  CA: 🇨🇦 加拿大
  FR: 🇫🇷 法国
  GB: 🇬🇧 英国
  KR: 🇰🇷 韩国
  DE: 🇩🇪 德国
  CN: 🇨🇳 中国
  RU: 🇷🇺 俄罗斯
  # SE: 🇸🇪 瑞典
  # CH: 🇨🇭 瑞士
  # EE: 🇪🇪 爱沙尼亚
